0.0num_envs: 256
num_eval_envs: 32
lr: 0.0003
max_it: 1000
max_grad_norm: 0.4
seed: 0
system_config: humanoid
demo_replay_mode: threshold
threshold: 0.4
normalize_observations: True
cycle_len: 130
ep_len: 65
ep_len_eval: 54
use_lr_scheduler: True
reward_scaling: 0.02
rot_weight: 0.5
vel_weight: 0.3
ang_weight: 0.01

deep_mimic_reward_weights:
  w_p: 0.65
  w_v: 0.1
  w_e: 0.15
  w_c: 0.1

deep_mimic_weights_factors:
  w_pose: 2
  w_angular: 0.1
  w_efector: 40
  w_com: 10




model: models/final_humanoid.xml

#ref: motions/humanoid3d_punch.txt
ref: motions/humanoid3d_punch_duplicated.txt
